version : 0.2


env:
    variables:
        S3_BUCKET: "bookstoredetailscodepipelinedemodetails"
APP_NAME: "newApp"
BUILD_ENV : "prod"

phases:
  install:
    runtime-versions:
        nodejs: 10
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started 
        - ng build
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    
       
